<a href="https://colab.research.google.com/github/theshashank1/cse-c5-3year-da/blob/main/Pandas_C1_C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd

In [28]:
marks = pd.Series([99, 35, 40, 55], index = ['Sci', 'Soc', 'Math', 'Eng' ], name = 'marks', dtype = 'str')
marks

Sci     99
Soc     35
Math    40
Eng     55
Name: marks, dtype: object

In [29]:
marks['Sci']

'99'

In [30]:
marks.shape

(4,)

In [31]:
marks.dtype

dtype('O')

In [32]:
df = pd.DataFrame({'Name' : ['Shashank', 'Sreeja', 'Sai Teja'],
                       'Marks': [100, 120, 130]})
df

       Name  Marks
0  Shashank    100
1    Sreeja    120
2  Sai Teja    130

In [33]:
df = pd.DataFrame([['Shashank', 100], ['s', 120], ['d', 50] ], columns= ['Name', 'Marks'] )
df

       Name  Marks
0  Shashank    100
1         s    120
2         d     50

In [34]:
df = pd.read_csv('/content/zepto.csv')

In [35]:
df.head(10)

,order_id,item,category,price,quantity,city,delivery_mins,order_date,plan
0,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime
1,102,Bread,Bakery,45,1,hyderabad,15,15-01-2025,NaN
2,103,maggi,Packaged Food,20,3,Bengaluru,10,2025-01-16,Free
3,104,Eggs (12),Dairy,₹84,1,Chennai,500,2025-01-16,Prime
4,105,Rice 5kg,Grocery,249,1,Hyderabad,18,16-01-2025,Free
5,106,Butter,Dairy,55,2,HYDERABAD,14,2025-01-17,NaN
6,107,PANEER,dairy,90,-1,Chennai,11,2025-01-17,Prime
7,108,Curd,Dairy,40,1,Bengaluru,9,2025-01-18,Free
8,109,Milk,Dairy,NaN,1,NaN,13,2025-01-18,Free
9,110,Bread,Bakery,45,0,hyderabad,16,2025-01-19,Prime

In [36]:
df.tail()

,order_id,item,category,price,quantity,city,delivery_mins,order_date,plan
7,108,Curd,Dairy,40,1,Bengaluru,9,2025-01-18,Free
8,109,Milk,Dairy,NaN,1,NaN,13,2025-01-18,Free
9,110,Bread,Bakery,45,0,hyderabad,16,2025-01-19,Prime
10,111,Oil 1L,Grocery,150,1,Hyderabad,-5,2025-01-19,NaN
11,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime