<a href="https://colab.research.google.com/github/theshashank1/cse-c5-3year-da/blob/main/tips.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
from scipy import stats

In [3]:
df = pd.read_csv('/content/tips.csv')

In [4]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [6]:
df['tip_pct'] = (df['tip'] / df['total_bill']) * 100

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
 7   tip_pct     244 non-null    float64
dtypes: float64(3), int64(1), object(4)
memory usage: 15.4+ KB

In [29]:
df.head(25)

    total_bill   tip     sex smoker  day    time  size    tip_pct
0        16.99  1.01  Female     No  Sun  Dinner     2   5.944673
1        10.34  1.66    Male     No  Sun  Dinner     3  16.054159
2        21.01  3.50    Male     No  Sun  Dinner     3  16.658734
3        23.68  3.31    Male     No  Sun  Dinner     2  13.978041
4        24.59  3.61  Female     No  Sun  Dinner     4  14.680765
5        25.29  4.71    Male     No  Sun  Dinner     4  18.623962
6         8.77  2.00    Male     No  Sun  Dinner     2  22.805017
7        26.88  3.12    Male     No  Sun  Dinner     4  11.607143
8        15.04  1.96    Male     No  Sun  Dinner     2  13.031915
9        14.78  3.23    Male     No  Sun  Dinner     2  21.853857
10       10.27  1.71    Male     No  Sun  Dinner     2  16.650438
11       35.26  5.00  Female     No  Sun  Dinner     4  14.180374
12       15.42  1.57    Male     No  Sun  Dinner     2  10.181582
13       18.43  3.00    Male     No  Sun  Dinner     4  16.277808
14       14.83  3.02  Female     No  Sun  Dinner     2  20.364127
15       21.58  3.92    Male     No  Sun  Dinner     2  18.164968
16       10.33  1.67  Female     No  Sun  Dinner     3  16.166505
17       16.29  3.71    Male     No  Sun  Dinner     3  22.774708
18       16.97  3.50  Female     No  Sun  Dinner     3  20.624632
19       20.65  3.35    Male     No  Sat  Dinner     3  16.222760
20       17.92  4.08    Male     No  Sat  Dinner     2  22.767857
21       20.29  2.75  Female     No  Sat  Dinner     2  13.553475
22       15.77  2.23  Female     No  Sat  Dinner     2  14.140774
23       39.42  7.58    Male     No  Sat  Dinner     4  19.228818
24       19.82  3.18    Male     No  Sat  Dinner     2  16.044400

In [9]:
# H0 = There is no difference %
# H1 = There is differnce in tip %

smoker_pct = df[df['smoker'] == 'Yes']['tip_pct']
non_smoker_pct = df[df['smoker'] == 'No']['tip_pct']

print(f'Smoker % : {smoker_pct.mean()}, {smoker_pct.std()}')
print(f'Non Smoker % : {non_smoker_pct.mean()}, {non_smoker_pct.std()}')

Smoker % : 16.319604463687792, 8.51191960613408
Non Smoker % : 15.932846217921526, 3.9909765363953524

In [13]:
# T-test

t_stat, p_val = stats.ttest_ind(smoker_pct, non_smoker_pct)
print(f't-stat : {t_stat}, p-val : {p_val}')

t-stat : 0.4796693002669833, p-val : 0.6318957776878545

In [16]:
# H0: There is no difference in tip by Gender
# H1: There is differ...
male_pct = df[df['sex'] == 'Male']['tip_pct']
female_pct = df[df['sex'] == 'Female']['tip_pct']

t_stat, p_val = stats.ttest_ind(male_pct, female_pct, equal_var=False)
print(f't-stat : {t_stat}, p-val : {p_val}')

t-stat : -1.1432770167349975, p-val : 0.2542456188927581

In [18]:
print(len(df[df['sex'] == 'Male']))
print(len(df[df['sex'] == 'Female']))

157
87

In [26]:
groups = []
for d in ['Thur', 'Fri', 'Sat', 'Sun'] :
  groups.append(df[df['day'] == d]['total_bill'])

In [27]:
for g in groups:
  print(g.mean(), g.std(), len(g))

17.682741935483868 7.886170333087846 62
17.15157894736842 8.302659723217143 19
20.441379310344825 9.480418641086723 87
21.41 8.832121828869889 76

In [28]:
f_stat, p_val = stats.f_oneway(*groups)
print(f'f-stat : {f_stat}, p-val : {p_val}')

f-stat : 2.767479443286335, p-val : 0.04245383328952047

In [31]:
contingency = pd.crosstab(df['time'], df['smoker'])
contingency

smoker   No  Yes
time
Dinner  106   70
Lunch    45   23

In [32]:
# H0 = Smoking status and meal time has no relationship
# H1 = Both are related.

chi2, p_val, dof, expected = stats.chi2_contingency(contingency)
print(f'chi2 : {chi2}, p-val : {p_val}, dof : {dof}')

chi2 : 0.5053733928754355, p-val : 0.4771485672079724, dof : 1

In [33]:
pd.DataFrame(expected, columns=contingency.columns, index=contingency.index)

smoker          No        Yes
time
Dinner  108.918033  67.081967
Lunch    42.081967  25.918033

In [35]:
contingency = pd.crosstab(df['sex'], df['smoker'])
contingency

smoker  No  Yes
sex
Female  54   33
Male    97   60

In [36]:
chi2, p_val, dof, expected = stats.chi2_contingency(contingency)
print(f'chi2 : {chi2}, p-val : {p_val}, dof : {dof}')

chi2 : 0.0, p-val : 1.0, dof : 1

In [37]:
pd.DataFrame(expected, columns=contingency.columns, index=contingency.index)

smoker         No        Yes
sex
Female  53.840164  33.159836
Male    97.159836  59.840164